/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package package_default;

import entity.Media;
import entity.Metric;
import entity.SoftwareRate;
import java.awt.Toolkit;
import java.io.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import support.Dialog;

/**
 *
 * @author caio
 */
public class Ferramentas extends javax.swing.JFrame {

    /**
     * Creates new form Ferramentas
     */
    public Ferramentas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jButton8 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jTextField9 = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jTextField11 = new javax.swing.JTextField();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox();
        jButton11 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton12 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jSpinner2 = new javax.swing.JSpinner();
        jButton13 = new javax.swing.JButton();

        setTitle("Ferramentas");
        setBounds(new java.awt.Rectangle(400, 200, 0, 0));
        setIconImage((new javax.swing.ImageIcon(getClass().getResource("/package_default/imgs/icon_tools.png"))).getImage());
        setPreferredSize(new java.awt.Dimension(579, 411));
        setResizable(false);

        jTabbedPane1.setPreferredSize(new java.awt.Dimension(574, 329));

        jPanel2.setPreferredSize(new java.awt.Dimension(574, 379));

        jTextField1.setText("jTextField1");

        jScrollPane2.setViewportView(jTree1);

        jScrollPane7.setPreferredSize(new java.awt.Dimension(200, 200));

        jTable4.setModel(new CustomTableModel(
            CustomTableModel.VIDEO_DATA,
            bridge.ServiceBridge.queryMediaList(new Media())
        )
    );
    jScrollPane7.setViewportView(jTable4);

    jButton8.setText("Próximo");
    jButton8.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton8ActionPerformed(evt);
        }
    });

    jButton1.setText("Voltar");

    jButton2.setText("Remover");

    jButton3.setText("Adicionar");
    jButton3.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton3ActionPerformed(evt);
        }
    });

    jButton4.setText("Configurar");
    jButton4.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton4ActionPerformed(evt);
        }
    });

    jButton9.setText("Editar");

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(jButton1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE))
                .addComponent(jTextField1)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jButton9)
                    .addGap(5, 5, 5)
                    .addComponent(jButton8))
                .addComponent(jScrollPane2))
            .addGap(10, 10, 10))
    );
    jPanel2Layout.setVerticalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButton8)
                .addComponent(jButton1)
                .addComponent(jButton3)
                .addComponent(jButton4)
                .addComponent(jButton9)
                .addComponent(jButton2))
            .addContainerGap())
    );

    jTabbedPane1.addTab("Gerador de Artefatos", jPanel2);
    jPanel2.setVisible(false);

    jTextField9.setText("Busca");
    jTextField9.setToolTipText("Digite um termo para busca e pressione enter.");
    jTextField9.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jTextField9ActionPerformed(evt);
        }
    });
    jTextField9.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            jTextField9FocusGained(evt);
        }
        public void focusLost(java.awt.event.FocusEvent evt) {
            jTextField9FocusLost(evt);
        }
    });

    jScrollPane5.setPreferredSize(new java.awt.Dimension(200, 200));

    tableAvaliador1 = new CustomTableModel(
        CustomTableModel.VIDEO_DATA,
        bridge.ServiceBridge.queryMediaList(new Media())
    );
    jTable2.setModel(tableAvaliador1);
    jScrollPane5.setViewportView(jTable2);

    jButton5.setText("H");
    jButton5.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton5ActionPerformed(evt);
        }
    });

    jButton10.setText("Iniciar");
    jButton10.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton10ActionPerformed(evt);
        }
    });

    jScrollPane8.setPreferredSize(new java.awt.Dimension(200, 200));

    tableAvaliador2 = new CustomTableModel(
        CustomTableModel.VIDEO_DATA,
        bridge.ServiceBridge.queryMediaList(new Media())
    );
    jTable5.setModel(tableAvaliador2
    );
    jScrollPane8.setViewportView(jTable5);

    jTextField11.setText("Busca");
    jTextField11.setToolTipText("Digite um termo para busca e pressione enter.");
    jTextField11.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jTextField11ActionPerformed(evt);
        }
    });
    jTextField11.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            jTextField11FocusGained(evt);
        }
        public void focusLost(java.awt.event.FocusEvent evt) {
            jTextField11FocusLost(evt);
        }
    });

    jScrollPane9.setPreferredSize(new java.awt.Dimension(200, 200));

    avaliadorTask = new ArrayList();
    tableAvaliadorTask = new CustomTableModel(
        CustomTableModel.METRIC_TASK,
        avaliadorTask);
    jTable6.setModel(tableAvaliadorTask
    );
    jScrollPane9.setViewportView(jTable6);

    comboAvaliador = new CustomComboBoxModel(
        CustomComboBoxModel.METRIC_DATA,
        bridge.ServiceBridge.queryMetricList());
    jComboBox1.setModel(comboAvaliador);
    jComboBox1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jComboBox1ActionPerformed(evt);
        }
    });

    jButton11.setText("Adicionar");
    jButton11.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton11ActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jButton5)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton10))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                        .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGap(12, 12, 12)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButton11)))))
            .addContainerGap())
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton11)))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButton10)
                .addComponent(jButton5))
            .addContainerGap())
    );

    jTabbedPane1.addTab("Avaliador Objetivo", jPanel1);

    jTable1.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
            {"Duração", null, null, null, null},
            {"Coluna 1", null, null, null, null}
        },
        new String [] {
            "", "Distribuição", "Parâmetro 1", "Parâmetro 2", "Parâmetro 3"
        }
    ) {
        Class[] types = new Class [] {
            java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
        };
        boolean[] canEdit = new boolean [] {
            false, true, true, true, true
        };

        public Class getColumnClass(int columnIndex) {
            return types [columnIndex];
        }

        public boolean isCellEditable(int rowIndex, int columnIndex) {
            return canEdit [columnIndex];
        }
    });
    jScrollPane1.setViewportView(jTable1);

    jButton12.setText("Gerar");
    jButton12.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton12ActionPerformed(evt);
        }
    });

    jLabel1.setText("Número de elementos:");

    jLabel2.setText("Nome do arquivo:");

    jSpinner1.addChangeListener(new javax.swing.event.ChangeListener() {
        public void stateChanged(javax.swing.event.ChangeEvent evt) {
            jSpinner1StateChanged(evt);
        }
    });

    jLabel3.setText("Colunas:");

    jSpinner2.setValue(2);
    jSpinner2.addChangeListener(new javax.swing.event.ChangeListener() {
        public void stateChanged(javax.swing.event.ChangeEvent evt) {
            jSpinner2StateChanged(evt);
        }
    });

    jButton13.setText("Abrir...");
    jButton13.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton13ActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
    jPanel4.setLayout(jPanel4Layout);
    jPanel4Layout.setHorizontalGroup(
        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel4Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jButton12))
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jSpinner2))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jTextField3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton13)))))
            .addContainerGap())
    );
    jPanel4Layout.setVerticalGroup(
        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel4Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel2)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton13))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1)
                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel3)
                .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jButton12)
            .addContainerGap())
    );

    jTabbedPane1.addTab("RaffleTool", jPanel4);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
	tableAvaliadorTask.printDebugData();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
        //buscar tableAvaliador1
        Media m = new Media();
        m.setTitle(jTextField9.getText());
        tableAvaliador1.refresh(bridge.ServiceBridge.queryMediaList(m));
	jTable2.revalidate();
        jTable2.repaint();
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
        Media m = new Media();
        m.setTitle(jTextField11.getText());
        tableAvaliador2.refresh(bridge.ServiceBridge.queryMediaList(m));
	jTable5.revalidate();
        jTable5.repaint();
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private String getParams(int row, String dist){
        String acc = "";
        if(dist.equals("constant")){
            if(jTable1.getValueAt(row, 2) == null) acc = "error";// TODO warning
            else acc = jTable1.getValueAt(row, 2).toString();
        } else if(dist.equals("uniform") || dist.equals("normal")){
            if(jTable1.getValueAt(row, 2) == null || jTable1.getValueAt(row, 3) == null ) acc = "error";// TODO warning
            else acc = jTable1.getValueAt(row, 2).toString() + "," + jTable1.getValueAt(row, 3).toString();
        } else if(dist.equals("triangular")){
            if(jTable1.getValueAt(row, 2) == null || jTable1.getValueAt(row, 3) == null || jTable1.getValueAt(row, 4) == null) acc = "error";// TODO warning
            else acc = jTable1.getValueAt(row, 2).toString() + "," + jTable1.getValueAt(row, 3).toString()+ "," + jTable1.getValueAt(row, 4).toString();
        } else acc = "error";
        return acc;
    }
    
    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        // Criar process
        // raffle -o raffleout.rff -u normal -r 2,6 -e 1000 -d uniform -p 1,5 -d constant -p 3 -d triangular -p 3,20,10
        String directory = System.getProperty("user.dir");
        if(jTextField3.getText().length() > 0){
            try{
                String param = "";
                List<String> parametros = new ArrayList<String>();
                parametros.add(directory+"/../../algoritmos/raffleTools");
                parametros.add("-o");
                parametros.add(jTextField3.getText());
                parametros.add("-u");
                if(jTable1.getValueAt(0, 1) == null){
                    //TODO warning
                    Dialog.msgError("Verifique se o tipo da distribuição e os parâmetros da duração estão corretos.", "Parâmetros incorretos");
                    return;
                } else{
                    parametros.add(jTable1.getValueAt(0, 1).toString());
                    parametros.add("-r");
                    param = this.getParams(0, jTable1.getValueAt(0, 1).toString());
                    if(param.equals("error")){ // TODO warning
                        Dialog.msgError("Verifique se o tipo da distribuição e os parâmetros estão corretos.", "Parâmetros incorretos");
                        return;
                    }
                    parametros.add(param);
                    parametros.add("-e");
                    parametros.add(jSpinner1.getValue().toString());
                    for(int i = 1; i < ((DefaultTableModel)jTable1.getModel()).getRowCount(); i++){
                        parametros.add("-d");
                        if(jTable1.getValueAt(i, 1) == null){
                            Dialog.msgError("Verifique se o tipo da distribuição está correto.", "Parâmetros incorretos");
                            return;
                        }
                        param = this.getParams(i, jTable1.getValueAt(i, 1).toString());
                        if(param.equals("error")){ // TODO warning
                            Dialog.msgError("Verifique se os parâmetros da distribuição estão corretos.", "Parâmetros incorretos");
                            return;
                        }
                        parametros.add(jTable1.getValueAt(i, 1).toString());
                        parametros.add("-p");
                        parametros.add(param);
                    }
                    for(int i = 0; i < parametros.size(); ++i) System.out.println(parametros.get(i));
                    //Process p = new ProcessBuilder(directory + "/../../algoritmos/raffleTools", "-o", "pbuilder.rff", "-u", "constant", "-r", "2", "-e", "100", "-d", "uniform", "-p", "1,5").start();
                    // TODO warning pedir confirmação!
                    if(Dialog.question("Gerar arquivo?", "Confirmação")){
                        Process p = new ProcessBuilder(parametros).start();
                        // TODO warning confirmar: deu certo!
                        Dialog.msgInfo("Arquivo gerado com sucesso.", "Confirmação");
                    }
                }
            } catch(java.io.IOException e){
                Dialog.msgError("Ocorreu um erro na geração do arquivo. Por favor, tente novamente.", "Processo de geração");
                return;
                //System.out.println("Erro io");
                //System.err.println(e);
            }
        } else{
            // TODO Display warning
            Dialog.msgError("Verifique o nome do arquivo a ser gerado.", "Arquivo de saída");
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jSpinner2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner2StateChanged
        // TODO add your handling code here:
        int newValue = Integer.valueOf(jSpinner2.getValue().toString());
        if(newValue < 2){
            jSpinner2.setValue(2);//(Object)new Integer(0));
        } else{
            DefaultTableModel t = ((DefaultTableModel)jTable1.getModel());
            if(oldRaffleColumns < newValue){
                if(t.getRowCount() == 0){
                    t.insertRow(t.getRowCount(), new Object[]{"Duração"});
                } else {
                    t.insertRow(t.getRowCount(), new Object[]{"Coluna "+t.getRowCount()});
                }
            } else if(t.getRowCount() > 2){
                t.removeRow(t.getRowCount()-1);
            }
        }
        oldRaffleColumns = Integer.valueOf(jSpinner2.getValue().toString());
    }//GEN-LAST:event_jSpinner2StateChanged

    private void jSpinner1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner1StateChanged
        // TODO add your handling code here:
        int newValue = Integer.valueOf(jSpinner1.getValue().toString());
        if(newValue < 0){
            jSpinner1.setValue(0);//(Object)new Integer(0));
        }
    }//GEN-LAST:event_jSpinner1StateChanged

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        String caminho = Dialog.getFile(Dialog.TipoGetFile.Abrir);
        jTextField3.setText(caminho);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
	//botao adicionar do Avaliador
	Media video, reference;
	Metric metric;
	if(jTable2.getSelectedRowCount() != 1 || jTable5.getSelectedRowCount() != 1){
	    Dialog.msgWarning("Selecione um vídeo em cada tabela!", "Aviso");
	    return;
	}
	video = (Media)tableAvaliador1.getAuxData(jTable2.getSelectedRow());
	reference = (Media)tableAvaliador2.getAuxData(jTable5.getSelectedRow());
	metric = (Metric)comboAvaliador.getAuxData(jComboBox1.getSelectedIndex());
	if(video.getWidth().compareTo(reference.getWidth()) != 0 || video.getHeigth().compareTo(reference.getHeigth()) != 0){
	    Dialog.msgWarning("As dimensões dos vídeos selecionados são diferentes!", "Aviso");
	    return;
	}
	avaliadorTask.add(new MetricTask(video, reference, metric));
	tableAvaliadorTask.refresh(avaliadorTask);
	jTable6.revalidate();
	jTable6.repaint();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
	// TODO add your handling code here:
	// botao iniciar Avaliador
	MetricTask task;
	String directory = System.getProperty("user.dir");
	String result;
	List<String> params;
	int exit;
	for (Object taskObj : avaliadorTask) {
	    try{
	    task = (MetricTask) taskObj;
	    params = new ArrayList<String>();
	    params.add(directory+"/../../algoritmos/metricTool");
	    params.add("-s");
	    params.add(task.getVideo().getWidth() + "x" + task.getVideo().getHeigth());
	    params.add("-i");
	    params.add(task.getVideo().getPath());
	    params.add("-r");
	    params.add(task.getReference().getPath());
	    params.add("-m");
	    params.add(task.getMetric().getName());
	    Process p = new ProcessBuilder(params).start();
	    InputStream pi = p.getInputStream();
	    exit = p.waitFor();
	    if(exit != 0){
		Dialog.msgError(printProcessOutput(pi), "Exit status " + exit);
		continue;
	    }
	    //TODO: capturar nota e salvar no banco
	    SoftwareRate sr = new SoftwareRate();
	    sr.setMedia(task.getVideo());
	    sr.setReferenceMedia(task.getReference());
	    sr.setMetric(task.getMetric());
	    result = printProcessOutput(pi);
	    sr.setValue(Double.parseDouble(result.substring(result.indexOf(':')+1)));
	    bridge.ServiceBridge.SaveOrUpdateSoftRate(sr);
	    Dialog.msgInfo("Métrica gravada com sucesso!", "Sucesso");
	    } catch (IOException ex){
		ex.printStackTrace();
	    } catch (InterruptedException ex){
		ex.printStackTrace();
	    }
	}
	avaliadorTask.clear();
	tableAvaliadorTask.refresh(avaliadorTask);
	jTable6.revalidate();
	jTable6.repaint();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jTextField9FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField9FocusGained
        // TODO add your handling code here:
        jTextField9.setText("");
    }//GEN-LAST:event_jTextField9FocusGained

    private void jTextField9FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField9FocusLost
        // TODO add your handling code here:
        jTextField9.setText("Busca");
    }//GEN-LAST:event_jTextField9FocusLost

    private void jTextField11FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField11FocusGained
        // TODO add your handling code here:
        jTextField11.setText("");
    }//GEN-LAST:event_jTextField11FocusGained

    private void jTextField11FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField11FocusLost
        // TODO add your handling code here:
        jTextField11.setText("Busca");
    }//GEN-LAST:event_jTextField11FocusLost

    public static String printProcessOutput(InputStream is) {
	if(is != null){
	    Writer writer = new StringWriter();
	    
	    char[] buffer = new char[1024];
	    try{
		Reader reader = new BufferedReader(new InputStreamReader(is, "UtF-8"));
		int n;
		while((n = reader.read(buffer)) != -1){
		    writer.write(buffer, 0, n);
		}
	    }catch (IOException ex){
	    }
	    return writer.toString();
	}
	else return "";
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ferramentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ferramentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ferramentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ferramentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Ferramentas().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBox1;
    private CustomComboBoxModel comboAvaliador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private CustomTableModel tableAvaliador1;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private CustomTableModel tableAvaliador2;
    private javax.swing.JTable jTable6;
    private CustomTableModel tableAvaliadorTask;
    private ArrayList avaliadorTask;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables
    private int oldRaffleColumns = 2;
}
