/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package package_default;

import entity.Media;
import entity.Metric;
import entity.SoftwareRate;
import java.io.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import support.Dialog;

/**
 *
 * @author caio
 */
public class Ferramentas extends javax.swing.JFrame {

    /**
     * Creates new form Ferramentas
     */
    public Ferramentas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jTextField10 = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jScrollPane11 = new javax.swing.JScrollPane();
        jTable8 = new javax.swing.JTable();
        jButton15 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jSpinner3 = new javax.swing.JSpinner();
        jTextField4 = new javax.swing.JTextField();
        jButton16 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSpinner4 = new javax.swing.JSpinner();
        jComboBox2 = new javax.swing.JComboBox();
        jButton14 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jButton17 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jTextField9 = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jTextField11 = new javax.swing.JTextField();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox();
        jButton11 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton12 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jSpinner2 = new javax.swing.JSpinner();
        jButton13 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setTitle("Ferramentas");
        setBounds(new java.awt.Rectangle(400, 200, 0, 0));
        setIconImage((new javax.swing.ImageIcon(getClass().getResource("/package_default/imgs/icon_tools.png"))).getImage());
        setPreferredSize(new java.awt.Dimension(579, 411));
        setResizable(false);

        jTabbedPane1.setPreferredSize(new java.awt.Dimension(574, 329));

        jPanel2.setPreferredSize(new java.awt.Dimension(574, 379));

        jTextField10.setText("Procure vídeos");
        jTextField10.setToolTipText("Digite um termo para busca e pressione enter.");
        jTextField10.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField10FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField10FocusLost(evt);
            }
        });
        jTextField10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField10KeyReleased(evt);
            }
        });

        jScrollPane6.setPreferredSize(new java.awt.Dimension(200, 200));

        tableGerador1 = new CustomTableModel(
            CustomTableModel.VIDEO_DATA,
            bridge.ServiceBridge.queryMediaList(new Media())
        );
        jTable3.setModel(tableGerador1);
        jTable3.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane6.setViewportView(jTable3);

        jScrollPane11.setPreferredSize(new java.awt.Dimension(200, 200));

        geradorTask = new ArrayList();
        tableGeradorTask = new CustomTableModel(
            CustomTableModel.GERADOR_TASK,
            geradorTask);
        jTable8.setModel(tableGeradorTask);
        jTable8.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane11.setViewportView(jTable8);

        jButton15.setText("Iniciar");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jButton6.setText("H");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jTabbedPane2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setText("Raffle:");

        jLabel5.setText("Resultado:");

        jButton1.setText("...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Janela:");

        jLabel8.setText("Níveis DCT:");

        jButton2.setText("...");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jSpinner3.setValue(1);
        jSpinner3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner3StateChanged(evt);
            }
        });

        jButton16.setText("Adicionar");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField2)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(44, 44, 44)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jSpinner3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 28, Short.MAX_VALUE))
                                    .addComponent(jTextField1))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton16))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(9, 9, 9)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jSpinner3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jButton16)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Block", jPanel3);

        jLabel7.setText("Resultado:");

        jButton3.setText("...");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel9.setText("Filtro:");

        jLabel10.setText("Tamanho:");

        jSpinner4.setValue(3);
        jSpinner4.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner4StateChanged(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "average", "median" }));

        jButton14.setText("Adicionar");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(40, 40, 40)
                        .addComponent(jComboBox2, 0, 156, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton14))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSpinner4, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(0, 61, Short.MAX_VALUE)
                        .addComponent(jButton14))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jSpinner4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane2.addTab("Blur", jPanel5);

        jButton17.setText("Adicionar");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jLabel11.setText("Resultado:");

        jButton4.setText("...");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel12.setText("Raffle:");

        jButton8.setText("...");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton17))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jTextField6, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(44, 44, 44)
                        .addComponent(jTextField7, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(jButton17)
                .addContainerGap())
        );

        jTabbedPane2.addTab("NetSim", jPanel6);

        jButton9.setText("Remover");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton15))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTabbedPane2)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane11, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton15)
                    .addComponent(jButton6)
                    .addComponent(jButton9))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Gerador de Artefatos", jPanel2);
        jPanel2.setVisible(false);

        jTextField9.setText("Busca");
        jTextField9.setToolTipText("Digite um termo para busca e pressione enter.");
        jTextField9.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField9FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField9FocusLost(evt);
            }
        });
        jTextField9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField9KeyReleased(evt);
            }
        });

        jScrollPane5.setPreferredSize(new java.awt.Dimension(200, 200));

        tableAvaliador1 = new CustomTableModel(
            CustomTableModel.VIDEO_DATA,
            bridge.ServiceBridge.queryMediaList(new Media())
        );
        jTable2.setModel(tableAvaliador1);
        jTable2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane5.setViewportView(jTable2);

        jButton5.setText("H");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton10.setText("Iniciar");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jScrollPane8.setPreferredSize(new java.awt.Dimension(200, 200));

        tableAvaliador2 = new CustomTableModel(
            CustomTableModel.VIDEO_DATA,
            bridge.ServiceBridge.queryMediaList(new Media())
        );
        jTable5.setModel(tableAvaliador2);
        jTable5.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane8.setViewportView(jTable5);

        jTextField11.setText("Busca");
        jTextField11.setToolTipText("Digite um termo para busca e pressione enter.");
        jTextField11.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField11FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField11FocusLost(evt);
            }
        });
        jTextField11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField11KeyReleased(evt);
            }
        });

        jScrollPane9.setPreferredSize(new java.awt.Dimension(200, 200));

        avaliadorTask = new ArrayList();
        tableAvaliadorTask = new CustomTableModel(
            CustomTableModel.METRIC_TASK,
            avaliadorTask);
        jTable6.setModel(tableAvaliadorTask
        );
        jScrollPane9.setViewportView(jTable6);

        comboAvaliador = new CustomComboBoxModel(
            CustomComboBoxModel.METRIC_DATA,
            bridge.ServiceBridge.queryMetricList());
        jComboBox1.setModel(comboAvaliador);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton11.setText("Adicionar");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton10))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton11)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton11)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton10)
                    .addComponent(jButton5))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Avaliador Objetivo", jPanel1);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Duração", null, null, null, null},
                {"Coluna 1", null, null, null, null}
            },
            new String [] {
                "", "Distribuição", "Parâmetro 1", "Parâmetro 2", "Parâmetro 3"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton12.setText("Gerar");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jLabel1.setText("Número de elementos:");

        jLabel2.setText("Nome do arquivo:");

        jSpinner1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner1StateChanged(evt);
            }
        });

        jLabel3.setText("Colunas:");

        jSpinner2.setValue(2);
        jSpinner2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner2StateChanged(evt);
            }
        });

        jButton13.setText("Abrir...");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton7.setText("H");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton12))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSpinner2))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jTextField3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton13)))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton12)
                    .addComponent(jButton7))
                .addContainerGap())
        );

        jTabbedPane1.addTab("RaffleTool", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        String caminho = Dialog.getFile(Dialog.TipoGetFile.Abrir);
        jTextField3.setText(caminho);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jSpinner2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner2StateChanged
        // TODO add your handling code here:
        int newValue = Integer.valueOf(jSpinner2.getValue().toString());
        if (newValue < 2) {
            jSpinner2.setValue(2);//(Object)new Integer(0));
        } else {
            DefaultTableModel t = ((DefaultTableModel) jTable1.getModel());
            if (oldRaffleColumns < newValue) {
                if (t.getRowCount() == 0) {
                    t.insertRow(t.getRowCount(), new Object[]{"Duração"});
                } else {
                    t.insertRow(t.getRowCount(), new Object[]{"Coluna " + t.getRowCount()});
                }
            } else if (t.getRowCount() > 2) {
                t.removeRow(t.getRowCount() - 1);
            }
        }
        oldRaffleColumns = Integer.valueOf(jSpinner2.getValue().toString());
    }//GEN-LAST:event_jSpinner2StateChanged

    private void jSpinner1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner1StateChanged
        // TODO add your handling code here:
        int newValue = Integer.valueOf(jSpinner1.getValue().toString());
        if (newValue < 0) {
            jSpinner1.setValue(0);//(Object)new Integer(0));
        }
    }//GEN-LAST:event_jSpinner1StateChanged

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        // Criar process
        // raffle -o raffleout.rff -u normal -r 2,6 -e 1000 -d uniform -p 1,5 -d constant -p 3 -d triangular -p 3,20,10
        String directory = System.getProperty("user.dir");
        if (jTextField3.getText().length() > 0) {
            try {
                String param = "";
                List<String> parametros = new ArrayList<String>();
                parametros.add(directory + "/../../algoritmos/raffle");
                parametros.add("-o");
                parametros.add(jTextField3.getText());
                parametros.add("-u");
                if (jTable1.getValueAt(0, 1) == null) {
                    //TODO warning
                    Dialog.msgError("Verifique se o tipo da distribuição e os parâmetros da duração estão corretos.", "Parâmetros incorretos");
                    return;
                } else {
                    parametros.add(jTable1.getValueAt(0, 1).toString());
                    parametros.add("-r");
                    param = this.getParams(0, jTable1.getValueAt(0, 1).toString());
                    if (param.equals("error")) { // TODO warning
                        Dialog.msgError("Verifique se o tipo da distribuição e os parâmetros estão corretos.", "Parâmetros incorretos");
                        return;
                    }
                    parametros.add(param);
                    parametros.add("-e");
                    parametros.add(jSpinner1.getValue().toString());
                    for (int i = 1; i < ((DefaultTableModel) jTable1.getModel()).getRowCount(); i++) {
                        parametros.add("-d");
                        if (jTable1.getValueAt(i, 1) == null) {
                            Dialog.msgError("Verifique se o tipo da distribuição está correto.", "Parâmetros incorretos");
                            return;
                        }
                        param = this.getParams(i, jTable1.getValueAt(i, 1).toString());
                        if (param.equals("error")) { // TODO warning
                            Dialog.msgError("Verifique se os parâmetros da distribuição estão corretos.", "Parâmetros incorretos");
                            return;
                        }
                        parametros.add(jTable1.getValueAt(i, 1).toString());
                        parametros.add("-p");
                        parametros.add(param);
                    }
                    //Process p = new ProcessBuilder(directory + "/../../algoritmos/raffleTools", "-o", "pbuilder.rff", "-u", "constant", "-r", "2", "-e", "100", "-d", "uniform", "-p", "1,5").start();
                    if (Dialog.question("Gerar arquivo?", "Confirmação")) {
                        Process p = new ProcessBuilder(parametros).start();
                        // TODO warning confirmar: deu certo!
                        Dialog.msgInfo("Arquivo gerado com sucesso.", "Confirmação");
                    }
                }
            } catch (java.io.IOException e) {
                Dialog.msgError("Ocorreu um erro na geração do arquivo. Por favor, tente novamente.", "Processo de geração");
                return;
            }
        } else {
            // TODO Display warning
            Dialog.msgError("Verifique o nome do arquivo a ser gerado.", "Arquivo de saída");
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        //botao adicionar do Avaliador
        Media video, reference;
        Metric metric;
        if (jTable2.getSelectedRowCount() != 1 || jTable5.getSelectedRowCount() != 1) {
            Dialog.msgWarning("Selecione um vídeo em cada tabela!", "Aviso");
            return;
        }
        video = (Media) tableAvaliador1.getAuxData(jTable2.getSelectedRow());
        reference = (Media) tableAvaliador2.getAuxData(jTable5.getSelectedRow());
        metric = (Metric) comboAvaliador.getAuxData(jComboBox1.getSelectedIndex());
        if (video.getWidth().compareTo(reference.getWidth()) != 0 || video.getHeigth().compareTo(reference.getHeigth()) != 0) {
            Dialog.msgWarning("As dimensões dos vídeos selecionados são diferentes!", "Aviso");
            return;
        }
        avaliadorTask.add(new MetricTask(video, reference, metric));
        tableAvaliadorTask.refresh(avaliadorTask);
        jTable6.revalidate();
        jTable6.repaint();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField11FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField11FocusLost
        // TODO add your handling code here:
        jTextField11.setText("Busca");
    }//GEN-LAST:event_jTextField11FocusLost

    private void jTextField11FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField11FocusGained
        // TODO add your handling code here:
        jTextField11.setText("");
    }//GEN-LAST:event_jTextField11FocusGained

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        // botao iniciar Avaliador
        MetricTask task;
        String directory = System.getProperty("user.dir");
        String result;
        List<String> params;
        int exit;
        for (Object taskObj : avaliadorTask) {
            try {
                task = (MetricTask) taskObj;
                params = new ArrayList<String>();
                params.add(directory + "/../../algoritmos/metric");
                params.add("-s");
                params.add(task.getVideo().getWidth() + "x" + task.getVideo().getHeigth());
                params.add("-i");
                params.add(task.getVideo().getPath());
                params.add("-r");
                params.add(task.getReference().getPath());
                params.add("-m");
                params.add(task.getMetric().getName());
                Process p = new ProcessBuilder(params).start();
                InputStream pi = p.getInputStream();
                exit = p.waitFor();
                if (exit != 0) {
                    Dialog.msgError(printProcessOutput(pi), "Exit status " + exit);
                    continue;
                }
                //TODO: capturar nota e salvar no banco
                SoftwareRate sr = new SoftwareRate();
                sr.setMedia(task.getVideo());
                sr.setReferenceMedia(task.getReference());
                sr.setMetric(task.getMetric());
                result = printProcessOutput(pi);
                sr.setValue(Double.parseDouble(result.substring(result.indexOf(':') + 1)));
                bridge.ServiceBridge.SaveOrUpdateSoftRate(sr);
                Dialog.msgInfo("Métrica gravada com sucesso!", "Sucesso");
            } catch (IOException ex) {
                ex.printStackTrace();
            } catch (InterruptedException ex) {
                ex.printStackTrace();
            }
        }
        avaliadorTask.clear();
        tableAvaliadorTask.refresh(avaliadorTask);
        jTable6.revalidate();
        jTable6.repaint();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        tableAvaliadorTask.printDebugData();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField9FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField9FocusLost
        // TODO add your handling code here:
        jTextField9.setText("Busca");
    }//GEN-LAST:event_jTextField9FocusLost

    private void jTextField9FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField9FocusGained
        // TODO add your handling code here:
        jTextField9.setText("");
    }//GEN-LAST:event_jTextField9FocusGained

    private void jTextField10FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField10FocusGained
        // TODO add your handling code here:
        jTextField10.setText("");
    }//GEN-LAST:event_jTextField10FocusGained

    private void jTextField10FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField10FocusLost
        // TODO add your handling code here:
        if(jTextField10.getText().equals("")) jTextField10.setText("Procure vídeos");
    }//GEN-LAST:event_jTextField10FocusLost

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // ---->>> BLUR BUTTON
        
        if(jTable3.getSelectionModel().isSelectionEmpty()){
            Dialog.msgWarning("Selecione um vídeo da tabela para continuar.", "Vídeo");
            return;
        }
        if(jTextField5.getText().length() == 0){
            Dialog.msgWarning("Escolha o nome do arquivo a ser gerado.", "Arquivo de saída");
            return;
        }
        if(jComboBox2.getSelectedIndex() == 0){
            Dialog.msgWarning("Filtro não selecionado.", "Filtro");
            return;
        }
//        // check if file already exists
        File f = new File(jTextField5.getText());
        if(f.exists()){
            if(!Dialog.question("Arquivo já existe. Deseja sobrescrevê-lo?", "Arquivo existente")){
                jTextField5.setText("");
                return;
            }
        }
        Media video;
        video = (Media) tableGerador1.getAuxData(jTable3.getSelectedRow());
        java.util.List<String> params = new java.util.ArrayList<String>();
        params.add(System.getProperty("user.dir") + "/../../algoritmos/blur");
        params.add("-i");
        params.add(video.getPath());
        params.add("-o");
        params.add(jTextField5.getText());
        params.add("-s");
        params.add(video.getWidth() + "x" + video.getHeigth());
        params.add("-b");
        params.add(jComboBox2.getSelectedItem().toString());
        params.add("-w");
        params.add(jSpinner4.getValue().toString());
        geradorTask.add(new GeradorTask(video, "blur", "", params, jTextField5.getText()));
        tableGeradorTask.refresh(geradorTask);
        jTable8.revalidate();
        jTable8.repaint();
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        if (Dialog.question("Prosseguir e aplicar os artefatos aos vídeos selecionados?", "Confirmação")) {
            GeradorTask task;
            String directory = System.getProperty("user.dir");
            String result;
	    Media m;
            int exit;
            for (Object taskObj : geradorTask) {
                try {
                    task = (GeradorTask) taskObj;
                    Process p = new ProcessBuilder(task.getParams()).start();
                    InputStream pi = p.getInputStream();
                    exit = p.waitFor();
                    if (exit != 0) {
                        Dialog.msgError(printProcessOutput(pi), "Exit status " + exit);
                        continue;
                    }
                    //TODO: Adicionar o novo vídeo no banco de dados
		    m = new Media(task.getVideo());
		    m.setTitle("nova midia");
		    m.setPath(task.getNewPath());
		    bridge.ServiceBridge.SaveOrUpdateMedia(m);
                } catch (IOException ex) {
                    ex.printStackTrace();
                } catch (InterruptedException ex) {
                    ex.printStackTrace();
                }
            }
        }
        Dialog.msgInfo("Vídeos gerados com sucesso!", "Geração de vídeos");
        geradorTask.clear();
        tableGeradorTask.refresh(avaliadorTask);
        jTable8.revalidate();
        jTable8.repaint();
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jSpinner3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner3StateChanged
        // TODO add your handling code here:
        if(Integer.valueOf(jSpinner3.getValue().toString()) < 1 ) jSpinner3.setValue(1);
    }//GEN-LAST:event_jSpinner3StateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String caminho = Dialog.getFile(Dialog.TipoGetFile.Abrir);
        jTextField2.setText(caminho);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String caminho = Dialog.getFile(Dialog.TipoGetFile.Abrir);
        jTextField1.setText(caminho);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String caminho = Dialog.getFile(Dialog.TipoGetFile.Abrir);
        jTextField5.setText(caminho);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jSpinner4StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner4StateChanged
        // TODO add your handling code here:
        if(Integer.valueOf(jSpinner4.getValue().toString()) < 3 ) jSpinner4.setValue(3);
    }//GEN-LAST:event_jSpinner4StateChanged

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // ---->>> BLOCK BUTTON
        
        // video não selecionado
        if(jTable3.getSelectionModel().isSelectionEmpty()){
            Dialog.msgWarning("Selecione um vídeo da tabela para continuar.", "Vídeo");
            return;
        }
        // output vazio
        if(jTextField2.getText().length() == 0){
            Dialog.msgWarning("Escolha o nome do arquivo a ser gerado.", "Arquivo de saída");
            return;
        }
//        COLOCAR NO LISTENER DO BOTAO INICIAR??
        // output ja existe
        File f = new File(jTextField2.getText());
        if(f.exists()){
            if(!Dialog.question("Arquivo de saída já existe. Deseja sobrescrevê-lo?", "Arquivo existente")){
                jTextField2.setText("");
                return;
            }
        }
        // raffle vazio
        if(jTextField1.getText().length() == 0){
            Dialog.msgWarning("Escolha o arquivo raffle a ser utilizado.", "Arquivo raffle");
            return;
        }
        // raffle não existe
        f = new File(jTextField1.getText());
        if(!f.exists()){
            Dialog.msgWarning("Arquivo raffle não existe.", "Arquivo raffle");
            return;
        }
        // niveis dct separados por vírgula?
        String dct = jTextField4.getText();
        if(dct.length() == 0){
            Dialog.msgWarning("Escolha os níveis DCT a serem eliminados, \nseparando-os por vírgula.", "Níveis DCT");
            return;
        } else {
            for(int i = 0; i < dct.length(); ++i){
                if(!Character.isDigit(dct.charAt(i)) && !(dct.charAt(i) == ',')){
                    Dialog.msgWarning("Parâmetros DCT incorretos. Digite os \nníveis separado-os por vírgula.", "Níveis DCT");
                    return;
                }
            }
        }
        // verificar se os níveis são válidos
        String niveis[] = dct.split(",");
        int limite = Integer.valueOf(jSpinner3.getValue().toString());
        limite = 2*limite - 1;
        for(int i = 0; i < niveis.length; ++i){
            if(Integer.valueOf(niveis[i]) > limite){
                Dialog.msgWarning("Nível DCT inválido. Para a janela \n selecionada, o limite é " + limite + ".", "Níveis DCT");
                return;
            }
        }
        Media video;
        video = (Media) tableGerador1.getAuxData(jTable3.getSelectedRow());
        java.util.List<String> params = new java.util.ArrayList<String>();
        params.add(System.getProperty("user.dir") + "/../../algoritmos/block");
        params.add("-i");
        params.add(video.getPath());
        params.add("-o");
        params.add(jTextField2.getText());
        params.add("-r");
        params.add(jTextField1.getText());
        params.add("-w");
        params.add(jSpinner3.getValue().toString());
        params.add("-l");
        params.add(jTextField4.getText());
        params.add("-s");
        params.add(video.getWidth() + "x" + video.getHeigth());
        geradorTask.add(new GeradorTask(video, "block", jTextField1.getText(), params, jTextField2.getText()));
        tableGeradorTask.refresh(geradorTask);
        jTable8.revalidate();
        jTable8.repaint();
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // ---->>> Netsim BUTTON
        
        // video não selecionado
        if(jTable3.getSelectionModel().isSelectionEmpty()){
            Dialog.msgWarning("Selecione um vídeo da tabela para continuar.", "Vídeo");
            return;
        }
        // output vazio
        if(jTextField6.getText().length() == 0){
            Dialog.msgWarning("Escolha o nome do arquivo a ser gerado.", "Arquivo de saída");
            return;
        }
        // output ja existe
        File f = new File(jTextField6.getText());
        if(f.exists()){
            if(!Dialog.question("Arquivo de saída já existe. Deseja sobrescrevê-lo?", "Arquivo existente")){
                jTextField6.setText("");
                return;
            }
        }
        // raffle vazio
        if(jTextField7.getText().length() == 0){
            Dialog.msgWarning("Escolha o arquivo raffle a ser utilizado.", "Arquivo raffle");
            return;
        }
        // raffle não existe
        f = new File(jTextField7.getText());
        if(!f.exists()){
            Dialog.msgWarning("Arquivo raffle não existe.", "Arquivo raffle");
            return;
        }
	
	Media video;
        video = (Media) tableGerador1.getAuxData(jTable3.getSelectedRow());
        java.util.List<String> params = new java.util.ArrayList<String>();
        params.add(System.getProperty("user.dir") + "/../../algoritmos/netsim");
        params.add("-i");
        params.add(video.getPath());
        params.add("-o");
        params.add(jTextField6.getText());
        params.add("-r");
        params.add(jTextField7.getText());
        geradorTask.add(new GeradorTask(video, "netsim", jTextField7.getText(), params, jTextField6.getText()));
        tableGeradorTask.refresh(geradorTask);
        jTable8.revalidate();
        jTable8.repaint();
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        //Caminho NetSim
	String caminho = Dialog.getFile(Dialog.TipoGetFile.Abrir);
	jTextField6.setText(caminho);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        //raffle NetSim
	String caminho = Dialog.getFile(Dialog.TipoGetFile.Abrir);
	jTextField7.setText(caminho);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        if(jTable8.getSelectionModel().isSelectionEmpty() || jTable8.getSelectedRow() >= geradorTask.size()){
            return;
        }
        geradorTask.remove(jTable8.getSelectedRow());
        tableGeradorTask.refresh(geradorTask);
        jTable8.revalidate();
        jTable8.repaint();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jTextField10KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField10KeyReleased
        // TODO add your handling code here:
        Media m = new Media();
        m.setTitle(jTextField10.getText());
        tableGerador1.refresh(bridge.ServiceBridge.queryMediaList(m));
        jTable3.revalidate();
        jTable3.repaint();
    }//GEN-LAST:event_jTextField10KeyReleased

    private void jTextField9KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField9KeyReleased
        // TODO add your handling code here:
        //buscar tableAvaliador1
        Media m = new Media();
        m.setTitle(jTextField9.getText());
        tableAvaliador1.refresh(bridge.ServiceBridge.queryMediaList(m));
        jTable2.revalidate();
        jTable2.repaint();
    }//GEN-LAST:event_jTextField9KeyReleased

    private void jTextField11KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField11KeyReleased
        // TODO add your handling code here:
        Media m = new Media();
        m.setTitle(jTextField11.getText());
        tableAvaliador2.refresh(bridge.ServiceBridge.queryMediaList(m));
        jTable5.revalidate();
        jTable5.repaint();
    }//GEN-LAST:event_jTextField11KeyReleased

    private String getParams(int row, String dist){
        String acc = "";
        if(dist.equals("constant")){
            if(jTable1.getValueAt(row, 2) == null) acc = "error";// TODO warning
            else acc = jTable1.getValueAt(row, 2).toString();
        } else if(dist.equals("uniform") || dist.equals("normal")){
            if(jTable1.getValueAt(row, 2) == null || jTable1.getValueAt(row, 3) == null ) acc = "error";// TODO warning
            else acc = jTable1.getValueAt(row, 2).toString() + "," + jTable1.getValueAt(row, 3).toString();
        } else if(dist.equals("triangular")){
            if(jTable1.getValueAt(row, 2) == null || jTable1.getValueAt(row, 3) == null || jTable1.getValueAt(row, 4) == null) acc = "error";// TODO warning
            else acc = jTable1.getValueAt(row, 2).toString() + "," + jTable1.getValueAt(row, 3).toString()+ "," + jTable1.getValueAt(row, 4).toString();
        } else acc = "error";
        return acc;
    }
    
    public static String printProcessOutput(InputStream is) {
	if(is != null){
	    Writer writer = new StringWriter();
	    
	    char[] buffer = new char[1024];
	    try{
		Reader reader = new BufferedReader(new InputStreamReader(is, "UtF-8"));
		int n;
		while((n = reader.read(buffer)) != -1){
		    writer.write(buffer, 0, n);
		}
	    }catch (IOException ex){
	    }
	    return writer.toString();
	}
	else return "";
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ferramentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ferramentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ferramentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ferramentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Ferramentas().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBox1;
    private CustomComboBoxModel comboAvaliador;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSpinner jSpinner3;
    private javax.swing.JSpinner jSpinner4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private CustomTableModel tableAvaliador1;
    private javax.swing.JTable jTable3;
    private CustomTableModel tableGerador1;
    private javax.swing.JTable jTable5;
    private CustomTableModel tableAvaliador2;
    private javax.swing.JTable jTable6;
    private CustomTableModel tableAvaliadorTask;
    private ArrayList avaliadorTask;
    private javax.swing.JTable jTable8;
    private CustomTableModel tableGeradorTask;
    private ArrayList geradorTask;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
    private int oldRaffleColumns = 2;
}
