/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package package_default;

import entity.Device;
import entity.Media;
import entity.Metric;
import entity.Session;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.sql.Date;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import sun.tools.jar.resources.jar;
import support.Dialog;

/**
 *
 * @author caio
 */
public class Sessao extends javax.swing.JFrame {

    /**
     * Creates new form Sessao
     */
    public Sessao() {
        initComponents();
        jPanel2.setVisible(false);
        jPanel3.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jSpinner1 = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton8 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jTextField8 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane11 = new javax.swing.JScrollPane();
        jTable8 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jTextField5 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jScrollPane12 = new javax.swing.JScrollPane();
        jTable9 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();

        setTitle("Sessão");
        setBounds(new java.awt.Rectangle(300, 200, 0, 0));
        setIconImage((new javax.swing.ImageIcon(getClass().getResource("/package_default/imgs/icon_sessao.png"))).getImage());
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro"));
        jPanel1.setPreferredSize(new java.awt.Dimension(520, 329));

        jLabel1.setText("Preencha todos os campos abaixo:");

        jLabel2.setText("Título");

        jLabel3.setText("Tipo");

        jLabel4.setText("Métrica");

        jLabel5.setText("Espectadores");

        jLabel6.setText("Descrição");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Item 1", "Item 2", "Item 3", "Item 4" }));

        comboSessaoMetrica = new CustomComboBoxModel(
            CustomComboBoxModel.SMETRIC_DATA,
            bridge.ServiceBridge.queryMetricList());
        jComboBox2.setModel(comboSessaoMetrica);

        jSpinner1.setValue(1);
        jSpinner1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner1StateChanged(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton8.setText("Próximo");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSpinner1)
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton8)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 61, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton8)
                .addContainerGap())
        );

        jPanel1.setBounds(0, 0, 530, 350);
        jLayeredPane1.add(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Seleção de Vídeos"));

        jTextField8.setText("Procure vídeos");
        jTextField8.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField8FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField8FocusLost(evt);
            }
        });
        jTextField8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField8KeyReleased(evt);
            }
        });

        jButton4.setText("?");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jScrollPane4.setPreferredSize(new java.awt.Dimension(200, 200));

        tablePlayer1 = new CustomTableModel(
            CustomTableModel.VIDEO_DATA,
            bridge.ServiceBridge.queryMediaList(new Media())
        );
        jTable1.setModel(tablePlayer1);
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        jScrollPane4.setViewportView(jTable1);

        jScrollPane11.setPreferredSize(new java.awt.Dimension(200, 200));

        sessionMedias = new ArrayList();
        tablePlayerTask = new CustomTableModel(
            CustomTableModel.VIDEO_DATA,
            sessionMedias);
        jTable8.setModel(tablePlayerTask);
        jScrollPane11.setViewportView(jTable8);

        jLabel7.setText("<html><u>Sequência</u></html>");

        jButton6.setText("Adicionar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Remover");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton1.setText("Próximo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton5.setText("Voltar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton7)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jTextField8))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(159, 159, 159)
                                .addComponent(jButton5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 12, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton7)
                    .addComponent(jButton1)
                    .addComponent(jButton5))
                .addContainerGap())
        );

        jPanel2.setBounds(0, 0, 530, 350);
        jLayeredPane1.add(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Seleção"));

        jTextField5.setText("Procurar dispositivos");
        jTextField5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField5FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField5FocusLost(evt);
            }
        });
        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField5KeyReleased(evt);
            }
        });

        jButton2.setText("Adicionar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Remover");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton9.setText("Iniciar");
        jButton9.setMaximumSize(new java.awt.Dimension(69, 30));
        jButton9.setMinimumSize(new java.awt.Dimension(69, 30));
        jButton9.setPreferredSize(new java.awt.Dimension(69, 30));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("Voltar");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jScrollPane6.setPreferredSize(new java.awt.Dimension(200, 200));

        tableDeviceAll = new CustomTableModel(
            CustomTableModel.DEVICE_DATA,
            bridge.ServiceBridge.queryDeviceList()
        );
        jTable3.setModel(tableDeviceAll);
        jTable3.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        jScrollPane6.setViewportView(jTable3);

        jScrollPane12.setPreferredSize(new java.awt.Dimension(200, 200));

        sessionDevices = new ArrayList();
        tableDeviceSelected = new CustomTableModel(
            CustomTableModel.DEVICE_DATA,
            sessionDevices);
        jTable9.setModel(tableDeviceSelected);
        jTable9.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        jScrollPane12.setViewportView(jTable9);

        jLabel8.setText("<html><u>Dispositivos</u></html>");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3))
                    .addComponent(jTextField5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane12, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                    .addComponent(jScrollPane12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        jPanel3.setBounds(0, 0, 530, 350);
        jLayeredPane1.add(jPanel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jSpinner1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner1StateChanged
        // TODO add your handling code here:
        if(Integer.valueOf(jSpinner1.getValue().toString()) < 1 ) jSpinner1.setValue(1);
    }//GEN-LAST:event_jSpinner1StateChanged

    private void jTextField8FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField8FocusGained
        // TODO add your handling code here:
        if(jTextField8.getText().equals("Procure vídeos")) jTextField8.setText("");
    }//GEN-LAST:event_jTextField8FocusGained

    private void jTextField8FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField8FocusLost
        // TODO add your handling code here:
        if(jTextField8.getText().equals("")) jTextField8.setText("Procure vídeos");
    }//GEN-LAST:event_jTextField8FocusLost

    private void jTextField8KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField8KeyReleased
        // TODO add your handling code here:
        Media m = new Media();
        m.setTitle(jTextField8.getText());
        tablePlayer1.refresh(bridge.ServiceBridge.queryMediaList(m));
        jTable1.revalidate();
        jTable1.repaint();
    }//GEN-LAST:event_jTextField8KeyReleased

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        // video não selecionado
        if(jTable1.getSelectionModel().isSelectionEmpty()){
            Dialog.msgWarning("Selecione um vídeo da tabela para continuar.", "Vídeo");
            return;
        }
        int selected[] = jTable1.getSelectedRows();
        for(int i = 0; i < selected.length; ++i){
            Media video;
            video = (Media) tablePlayer1.getAuxData(selected[i]);
            sessionMedias.add(video);
        }
        tablePlayerTask.refresh(sessionMedias);
        jTable8.revalidate();
        jTable8.repaint();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        if(jTable8.getSelectionModel().isSelectionEmpty() || jTable8.getSelectedRow() >= sessionMedias.size()){
            return;
        }
        int selected[] = jTable8.getSelectedRows();
        for(int i = 0; i < selected.length; ++i){
            sessionMedias.remove(selected[i]-i);
        }
        tablePlayerTask.refresh(sessionMedias);
        jTable8.revalidate();
        jTable8.repaint();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        if(jTextField1.getText().length() == 0){
            Dialog.msgWarning("Escolha um nome para a sessão.", "Sessão");
            return;
        }
        if(jComboBox1.getSelectedIndex() == 0){
            Dialog.msgWarning("Escolha um tipo.", "Sessão");
            return;
        }
        if(Integer.valueOf(jSpinner1.getValue().toString()) == 0){
            Dialog.msgWarning("Escolha o número de espectadores.", "Sessão");
            return;
        }
        
        jPanel1.setVisible(false);
        jPanel2.setVisible(true);
        jPanel3.setVisible(false);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(sessionMedias.isEmpty()){
            Dialog.msgWarning("Não foram selecionados\nvídeos para a sessão.", "Sessão");
            return;
        }
        if(jComboBox2.getModel().getSelectedItem().toString().equals("DSIS")){
            if(sessionMedias.size()%2 != 0){
                Dialog.msgWarning("Para a métrica DSIS, é necessário\num número par de vídeos.", "Sessão");
                return;
            }
        }
        jPanel1.setVisible(false);
        jPanel2.setVisible(false);
        jPanel3.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        jPanel1.setVisible(true);
        jPanel2.setVisible(false);
        jPanel3.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        jPanel1.setVisible(false);
        jPanel2.setVisible(true);
        jPanel3.setVisible(false);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(jTable3.getSelectionModel().isSelectionEmpty()){
            Dialog.msgWarning("Selecione um vídeo da tabela para continuar.", "Sessão");
            return;
        }
        int selected[] = jTable3.getSelectedRows();
        for(int i = 0; i < selected.length; ++i){
            Device device;
            device = (Device) tableDeviceAll.getAuxData(selected[i]);
            if(sessionDevices.contains(device)){
                Dialog.msgWarning("Os dispositivos são de uso individual.", "Sessão");
                return;
            } else {
                sessionDevices.add(device);
            }
        }
        tableDeviceSelected.refresh(sessionDevices);
        jTable9.revalidate();
        jTable9.repaint();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(jTable9.getSelectionModel().isSelectionEmpty() || jTable9.getSelectedRow() >= sessionDevices.size()){
            return;
        }
        int selected[] = jTable9.getSelectedRows();
        for(int i = 0; i < selected.length; ++i){
            sessionDevices.remove(selected[i]-i);
        }
        tableDeviceSelected.refresh(sessionDevices);
        jTable9.revalidate();
        jTable9.repaint();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        //Botao Iniciar sessão
        if(jTable9.getRowCount() == 0){
            Dialog.msgWarning("Selecione algum dispositivo\npara continuar.", "Sessão");
            return;
        }
        int espectadores = Integer.valueOf(jSpinner1.getValue().toString());
        if(jTable9.getRowCount() < espectadores){
            Dialog.msgWarning("Faltam dispositivos. Nesta sessão,\nparticiparão "+espectadores+" espectador"+ ((espectadores > 1) ? "es.": "."), null);
            return;
        }
	Session s;
	ArrayList sessionArgs = new ArrayList();
	sessionArgs.add(jTextField1.getText()); //titulo
	sessionArgs.add(jComboBox1.getSelectedIndex());//tipo
	sessionArgs.add((Metric) comboSessaoMetrica.getAuxData(jComboBox2.getSelectedIndex()));//metrica
	sessionArgs.add(Integer.parseInt(jSpinner1.getValue().toString()));// espectadores
	sessionArgs.add(jTextArea1.getText());//descricao
        if(Dialog.question("Deseja iniciar sessão?", "Sessão")){
            //s = bridge.ServiceBridge.operationStartSession(sessionArgs, sessionMedias, bridge.ServiceBridge.queryDeviceList());
	    if(jComboBox2.getModel().getSelectedItem().toString().equals("DSIS")){
                PlayVideo playVideo = new PlayVideo(sessionMedias);
                new javax.swing.Timer(100, playVideo).start();
            }
            //System.out.println("Session ID -> " + s.getId());
//            // Mostrar painel inicial novamente
//            jPanel1.setVisible(true);
//            jPanel2.setVisible(false);
//            jPanel3.setVisible(false);
//            // Selecionar valores padroes
//            // painel inicial
//            jTextField1.setText("");
//            jComboBox1.setSelectedIndex(0);
//            jComboBox2.setSelectedIndex(0);
//            jSpinner1.setValue(1);
//            jTextArea1.setText("");
//            // painel intermediario
//            jTextField8.setText("Procure vídeos");
//            for(int i = 0; !sessionMedias.isEmpty(); ++i) sessionMedias.remove(0);
//            tablePlayerTask.refresh(sessionMedias);
//            jTable8.revalidate();
//            jTable8.repaint();
//            Media m = new Media();
//            m.setTitle("");
//            tablePlayer1.refresh(bridge.ServiceBridge.queryMediaList(m));
//            jTable1.revalidate();
//            jTable1.repaint();
//            // painel devices
//            jTextField5.setText("Procurar dispositivos");
//            for(int i = 0; !sessionDevices.isEmpty(); ++i) sessionDevices.remove(0);
//            tableDeviceAll.refresh(bridge.ServiceBridge.queryDeviceList());
//            jTable3.revalidate();
//            jTable3.repaint();
	}
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jTextField5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField5FocusGained
        // TODO add your handling code here:
        if(jTextField5.getText().equals("Procurar dispositivos")) jTextField5.setText("");
    }//GEN-LAST:event_jTextField5FocusGained

    private void jTextField5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField5FocusLost
        // TODO add your handling code here:
        if(jTextField5.getText().equals("")) jTextField5.setText("Procurar dispositivos");
    }//GEN-LAST:event_jTextField5FocusLost

    private void jTextField5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyReleased
        // TODO add your handling code here:
        ArrayList devices = bridge.ServiceBridge.queryDeviceList();
        for(int i = 0; i < devices.size(); ++i){
            if(!((Device)devices.get(i)).getName().toLowerCase().contains(jTextField5.getText().toLowerCase())){
                devices.remove(i);
            }
        }
        tableDeviceAll.refresh(devices);
        jTable3.revalidate();
        jTable3.repaint();
    }//GEN-LAST:event_jTextField5KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sessao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sessao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sessao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sessao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Sessao().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private CustomComboBoxModel comboSessaoMetrica;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable jTable1;
    private CustomTableModel tablePlayer1;
    private javax.swing.JTable jTable3;
    private CustomTableModel tableDeviceAll;
    private javax.swing.JTable jTable8;
    private CustomTableModel tablePlayerTask;
    private ArrayList sessionMedias;
    private javax.swing.JTable jTable9;
    private CustomTableModel tableDeviceSelected;
    private ArrayList sessionDevices;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}

class Painel extends javax.swing.JPanel{
    private String str;
    private String exit = "ESC para interromper";
    public Painel(){
        this.setLayout(null);
        this.setOpaque(false);
        this.setSize(Util.getScreenSize());
        this.setBackground(Color.red);
        this.setForeground(Color.WHITE);
    }
    public void setString(String s){
        this.str = s;
        repaint();
    }
    @Override
    protected void paintComponent(java.awt.Graphics g){
        super.paintComponent(g);
        java.awt.Graphics2D g2d = ((java.awt.Graphics2D) g);
        g2d.setColor(Color.black);
        g2d.fillRect(0, 0, this.getWidth(), this.getHeight());
        if(str.length() > 0){
            // draw main string
            g2d.setColor(Color.white);
            g2d.setFont(new java.awt.Font("Serif", java.awt.Font.PLAIN, 80));
            int slen = (int)g2d.getFontMetrics().getStringBounds(str, g2d).getWidth();
            int start = this.getWidth()/2 - slen/2;
            g2d.drawString(str, 0+start, this.getHeight()/2);
            // draw exit
            g2d.setFont(new java.awt.Font("Serif", java.awt.Font.PLAIN, 20));
            slen = (int)g2d.getFontMetrics().getStringBounds(exit, g2d).getWidth();
            start = this.getWidth()/2 - slen/2;
            g2d.drawString(exit, 0+start, this.getHeight()-20-(int)g2d.getFontMetrics().getStringBounds(exit, g2d).getHeight());
        }
        this.revalidate();
    }
    }
    class PlayVideo extends javax.swing.AbstractAction{
    private int CONFIGS = -1, INICIO = 0, PLAYING1 = 1, PLAYING2 = 2, AVALIACAO = 3, FIMSESSAO = 4, INTERROMPER = 5;
    private String cmd;
    private ArrayList medias;
    private javax.swing.JFrame blackScreen;
    private Painel blackPanel;
    private java.awt.GraphicsDevice gd;
    private int estado = CONFIGS;
    private int mediaPlaying = 0;

    public PlayVideo(ArrayList al){
        medias = al; 
        gd = java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice();
        blackScreen = new javax.swing.JFrame();
        blackScreen.setUndecorated(true);
        blackScreen.setSize(Util.getScreenSize());
        //blackScreen.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        blackScreen.setAlwaysOnTop(true);
        blackScreen.setLocationRelativeTo(null);
        blackScreen.addKeyListener(new java.awt.event.KeyListener(){
            @Override
            public void keyTyped(KeyEvent ke) {
            }

            @Override
            public void keyPressed(KeyEvent ke) {
            }

            @Override
            public void keyReleased(KeyEvent ke) {
                if(ke.getKeyCode() == 27){
                    estado = INTERROMPER;
                    blackScreen.setVisible(false);
                }
            }
        });
        blackPanel = new Painel();
        blackScreen.setLayout(null);
        blackScreen.add(blackPanel);
    }
    @Override
    public void actionPerformed(ActionEvent ae) {
        /* Sequencia http://docs.oracle.com/javase/tutorial/extra/fullscreen/exclusivemode.html
         *  painel com titulo por X segundos
         *  video
         *  troca titulo painel
         *  loop
         */
        ((javax.swing.Timer)ae.getSource()).stop();
        if(estado == CONFIGS){
            blackScreen.setVisible(true);
            gd.setFullScreenWindow(blackScreen);
            estado = INICIO;
        }
        if(estado == FIMSESSAO){
            blackScreen.setVisible(false);
        }
        if(estado == INTERROMPER){
            return;
        }
        if(mediaPlaying < medias.size()){
            if(estado == INICIO){
                blackPanel.setString(((Media)medias.get(mediaPlaying)).getTitle());
                ((javax.swing.Timer)ae.getSource()).setInitialDelay(2000);
                ((javax.swing.Timer)ae.getSource()).restart();
                estado = PLAYING1;
            } else if(estado == PLAYING1){
                blackPanel.setString("");
                cmd = "mplayer -slave -quiet -fs ";
                if(((Media)medias.get(mediaPlaying)).getPath().toLowerCase().contains(".yuv")){
                    cmd += "-demuxer rawvideo -rawvideo ";
                    cmd += "w=" + ((Media)medias.get(mediaPlaying)).getWidth();
                    cmd += ":h=" + ((Media)medias.get(mediaPlaying)).getHeigth();
                }
                cmd += " " + ((Media)medias.get(mediaPlaying)).getPath();
                // apaga texto da blackScreen
                try {
                    Process mplayerProcess = Runtime.getRuntime().exec(cmd);
                    mplayerProcess.waitFor();
                } catch (InterruptedException ex) {
                } catch (java.io.IOException ex){
                }
                ((javax.swing.Timer)ae.getSource()).setInitialDelay(10);
                ((javax.swing.Timer)ae.getSource()).restart();
                estado = PLAYING2;
            } else if(estado == PLAYING2){
                /* APRESENTAÇÃO DO SEGUNDO VIDEO: METRICA DSIS */
                cmd = "mplayer -slave -quiet -fs ";
                if(((Media)medias.get(mediaPlaying)).getPath().toLowerCase().contains(".yuv")){
                    cmd += "-demuxer rawvideo -rawvideo ";
                    cmd += "w=" + ((Media)medias.get(mediaPlaying+1)).getWidth();
                    cmd += ":h=" + ((Media)medias.get(mediaPlaying+1)).getHeigth();
                }
                cmd += " " + ((Media)medias.get(mediaPlaying+1)).getPath();
                try {
                    Process mplayerProcess = Runtime.getRuntime().exec(cmd);
                    mplayerProcess.waitFor();
                } catch (InterruptedException ex) {
                } catch (java.io.IOException ex){
                }
                blackPanel.setString("Avaliação " + ((Media)medias.get(mediaPlaying)).getTitle());
                ((javax.swing.Timer)ae.getSource()).setInitialDelay(7000);
                ((javax.swing.Timer)ae.getSource()).restart();
                estado = AVALIACAO;
            } else if(estado == AVALIACAO){
                // Metrica DSIS toca dois videos por vez para analisar o segundo
                mediaPlaying+=2;
                ((javax.swing.Timer)ae.getSource()).setInitialDelay(50);
                ((javax.swing.Timer)ae.getSource()).restart();
                estado = INICIO;
            }
        } else {
            blackPanel.setString("Fim da Sessão");
            ((javax.swing.Timer)ae.getSource()).setInitialDelay(2000);
            ((javax.swing.Timer)ae.getSource()).restart();
            estado = FIMSESSAO;
        }
    }
}